name: micard
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
     - family: Pacifico
       fonts:
         - asset: font/Pacifico-Regular.ttf

     - family: Source Sans Pro
       fonts:
         - asset: font/SourceSansPro-Regular.ttf
